ci(workflows): 修复stable构建中检出iborder分支的逻辑
添加分支存在性检查，当iborder分支不存在时直接终止流程并报错，避免后续执行出错

diff --git a/.github/workflows/firmware-stable.yml b/.github/workflows/firmware-stable.yml
--- a/.github/workflows/firmware-stable.yml
+++ b/.github/workflows/firmware-stable.yml
@@ -598,9 +598,15 @@ jobs:
           cd /tmp/$REPO_NAME
           echo "current branch: $(git branch), prepare to checkout iborder branch"
           git fetch --all
-          git branch -a | grep iborder
-          git checkout iborder
-          echo "iborder branch checked out successfully"
+          echo "fetched all branches"
+          if [ $(git branch -a | grep iborder ]; then
+            echo "iborder branch found"
+            git checkout iborder 
+            echo "iborder branch checked out successfully"
+          else
+            echo "iborder branch not found"
+            exit 1
+          fi
 
           cd $GITHUB_WORKSPACE
           # fix jct
